### ISSUE TITLE
Suppport autofixing for shorthand properties

### ISSUE THREAD

**Issue by nekitk** [CSSSR/dsgen#15]
```css
.component {
  padding: 10px;
  margin: 10px 0;
}

/* becomes */
.component {
  padding: var(--spacing-s);
  margin: 10px 0;
}
```
`margin` should be replaced with `var(--spacing-s) 0`
